services:

  postgres:
    image: postgres:16
    container_name: batch-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: batch-airflow
    depends_on:
      - postgres
    ports:
      - "8083:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@batch-postgres:5432/${AIRFLOW_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - /home/sheriff/projects/batch-data-pipeline/dbt:/opt/airflow/dbt
    command: standalone
    restart: unless-stopped

  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    container_name: batch-dbt
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /home/sheriff/projects/batch-data-pipeline/dbt:/usr/app/dbt
    working_dir: /usr/app/dbt
    command: ["dbt", "run", "--profiles-dir", "/usr/app/dbt/profiles"]

volumes:
  postgres_data:
