version: 2

sources:
  - name: raw
    description: "Raw transaction data loaded into PostgreSQL."

    schema: raw

    tables:
      - name: transactions
        description: "Validated Online Retail transactions."

        columns:
          - name: invoice_no
            data_tests:
              - not_null

          - name: stock_code
            data_tests:
              - not_null

          - name: quantity
            data_tests:
              - not_null

          - name: invoice_date
            data_tests:
              - not_null

          - name: unit_price
            data_tests:
              - not_null

          - name: country
            data_tests:
              - not_null